// layout.tsx

import type { Metadata } from "next";
import { TrackingProvider } from "@/context/TrackingContext";
import { EngagesProvider } from "@/context/EngageContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <EngagesProvider>
    <TrackingProvider>
        {children}
    </TrackingProvider>
    </EngagesProvider>
  );
}
